name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - Master  # Trigger on push to main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: fama-french-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytest httpx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest
  deploy:
    needs: test 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Submit
        # standard format: region-docker.pkg.dev / project_id / repo_name / image_name
        run: gcloud builds submit api --tag us-central1-docker.pkg.dev/fama-french-foxparadeafk/fama-french/fama-french-foxparade

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fama-french-foxparade \
            --image gcr.io/fama-french-foxparadeafk/fama-french-foxparade \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
